# -*- coding: utf-8 -*-
"""codeQR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12j86H4V3_1bjcx5n8iyl952beoeYc684
"""

!pip install qrcode[pil]

1

from google.colab import files
uploaded = files.upload()
logo_path = list(uploaded.keys())[0]
print(logo_path)

from google.colab import files
import qrcode

def generar_qr(texto, nombre_archivo="codigo_qr.png"):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_H,  # Mayor corrección de errores
        box_size=30,  # Tamaño más grande para mayor claridad
        border=4,
    )
    qr.add_data(texto)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")  # Colores de alto contraste
    img.save(nombre_archivo)
    print(f"Código QR generado y guardado como {nombre_archivo}")
    return nombre_archivo

texto = input("Ingresa el texto o URL para generar el código QR: ")
archivo_qr = generar_qr(texto, "usta_optimo.png")
files.download(archivo_qr)

from google.colab import files
files.download('usta.png')

